/*
BOOK_LEND_REOCRD	BOOK_ID				--2
					KEEPER_ID			--1
					LEND_DATE

MEMEBER_M			USER_ID				--1
					USER_CNAME
					USER_ENAME

BOOK_DATA			BOOK_ID				--2
					BOOK_BOUGHT_DATE
					BOOK_STATUS			--3
					BOOK_AMOUNT
					BOOK_CLASS_ID		--4

BOOK_CODE			CODE_ID				--3

BOOK_CLASS			BOOK_CLASS_ID		--4
					BOOK_CLASS_NAME


*/
SELECT bd.BOOK_ID AS 書本ID,
	FORMAT(bd.BOOK_BOUGHT_DATE, 'd', 'zh-TW') AS 購書日期,
	FORMAT(blr.LEND_DATE, 'd', 'zh-TW') AS 借閱日期,
	bcla.BOOK_CLASS_ID + '-' + bcla.BOOK_CLASS_NAME AS 書籍類別
	,blr.KEEPER_ID+'-'+mm.USER_CNAME+'('+mm.USER_ENAME+')' AS 借閱人,
	bd.BOOK_STATUS + '-' + bcod.CODE_NAME AS 狀態,
	REPLACE(CONVERT(NVARCHAR(20),CAST(bd.BOOK_AMOUNT AS Money) ,1),'.00','') + '元' AS 購買金額

FROM BOOK_LEND_RECORD AS blr
LEFT JOIN BOOK_DATA AS bd
	ON blr.BOOK_ID = bd.BOOK_ID
LEFT JOIN MEMBER_M AS mm
	ON blr.KEEPER_ID = mm.[USER_ID]
LEFT JOIN BOOK_CLASS AS bcla
	ON bd.BOOK_CLASS_ID = bcla.BOOK_CLASS_ID
LEFT JOIN BOOK_CODE AS bcod
	ON bd.BOOK_STATUS =  bcod.CODE_ID
WHERE blr.KEEPER_ID = 0002
ORDER BY bd.BOOK_AMOUNT DESC



