DELETE FROM BOOK_LEND_RECORD
WHERE BOOK_LEND_RECORD.BOOK_ID = 2004

SELECT bd.BOOK_ID AS 書本ID,
	FORMAT(bd.BOOK_BOUGHT_DATE, 'd', 'zh-TW') AS 購書日期,
	FORMAT(blr.LEND_DATE, 'd', 'zh-TW') AS 借閱日期,
	bcla.BOOK_CLASS_ID + '-' + bcla.BOOK_CLASS_NAME AS 書籍類別
	,blr.KEEPER_ID+'-'+mm.USER_CNAME+'('+mm.USER_ENAME+')' AS 借閱人,
	bd.BOOK_STATUS + '-' + bcod.CODE_NAME AS 狀態,
	FORMAT(bd.BOOK_AMOUNT,'d', 'zh-TW')+'元' AS 購買金額
FROM BOOK_LEND_RECORD AS blr
LEFT JOIN BOOK_DATA AS bd
	ON blr.BOOK_ID = bd.BOOK_ID
LEFT JOIN MEMBER_M AS mm
	ON blr.KEEPER_ID = mm.[USER_ID]
LEFT JOIN BOOK_CLASS AS bcla
	ON bd.BOOK_CLASS_ID = bcla.BOOK_CLASS_ID
LEFT JOIN BOOK_CODE AS bcod
	ON bd.BOOK_STATUS =  bcod.CODE_ID
WHERE blr.KEEPER_ID = 0002
ORDER BY bd.BOOK_AMOUNT DESC
